version: 1.0.{build}

environment:
  matrix:
    - nodejs_version: "20"
    - SERVER_IP: "160.85.252.80"
    - SERVER_USERNAME: "ubuntu"

cache:
  - node_modules

install:
  # Install Node.js and npm
  - ps: Install-Product node $env:nodejs_version $env:nodejs_architecture
  - node -v
  - npm -v

  # Install dependencies
  - npm install

build_script:
  # Run linting (if applicable)
  - npm run lint

  # Run tests
  - npm test

  # Build Next.js project
  - npm run build

deploy_script:
  # Decrypt SSH private key
  - ps: $key = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:SSH_PRIVATE_KEY))

  # Delete existing file before creating a new one
  - ps: Remove-Item -Path $env:USERPROFILE\.ssh\id_rsa -ErrorAction SilentlyContinue
  - ps: New-Item -Path $env:USERPROFILE\.ssh -Name "id_rsa" -Value $key

  # Set permissions for SSH private key file
  - ps: icacls $env:USERPROFILE\.ssh\id_rsa /inheritance:r
  - ps: icacls $env:USERPROFILE\.ssh\id_rsa /grant:r "$env:USERNAME:R"

  # Secure copy built files to server using SSH
  - ps: scp -i $env:USERPROFILE\.ssh\id_rsa -r ./out $env:SERVER_USERNAME@$env:SERVER_IP:/var/www/solar-system-simulator-website
